### ISSUE TITLE
QTLinguist standaloen distribution

### ISSUE THREAD

**Issue by bovirus** [lelegard/qtlinguist-installers#1]
@lelegard 

Could you please create standalone QTLinguist installer (ex. 5.9.0) for Windows/Linux/Mac and post in some host.

Thanks.

**Comment by lelegard** [comment]
The installers for Qt Linguist 5.9.0 have been just generated in the [release section](https://github.com/lelegard/qtlinguist-installers/releases/tag/v5.9.0) for macOS and Windows.

As explained in the project home page, there is no standalone installer for Linux since most Linux distros already provide a segmented installation of Qt without downloading and installing the multi-giga-bytes single Qt installer.

**Comment by bovirus** [comment]
Please update the reease versions with latest 5.9.0. Thanks.
