### ISSUE TITLE
Qt Linguist 10.1 - Didn't work with Italian language (added)

### ISSUE THREAD

**Issue by bovirus** [lelegard/qtlinguist-installers#14]
@lelegard 

I used QT 5.10.,0 with your script (Ia dedd Italin language for QT-Linguist) and I created standone with QT Lingist and Italian language works fine.

Now the QT Team released QT 5.10.1.

I made the same job.

I uninstalled QT 5.10.0
I installed QT 5.10.1

I copied the Qt Linguist Italian language in the folder.

I I ran QT Linguist from QT SDK folder it works in Italian.

Using the same Qt.Linguist standalone script (yours) now the portable and installrr version works fine, but when I run your QT Linguist didn't start in Italian (starts in English) also if the relative language file is present.

What's about it?

Whats the configuration (modules) that you suggest to check during QT SDK installation?

[Linguist_it.zip](https://github.com/lelegard/qtlinguist-installers/files/1884286/Linguist_it.zip)

Thanks. Bye.

**Comment by lelegard** [comment]
Hi,

I just recreated the installers v5.10.1 from the current scripts, without modifications. Installed on a standard Windows 10 VM without Qt SDK, Qt Linguist works fine in French, either using the installer or the standalone version.

The installers were created on another Windows 10 VM with Qt 5.10.1 SDK installed, basic options (see snapshot below). Note that I did not _copy_ any language file, just:
- uninstalled Qt 5.10.0
- installed Qt 5.10.1 with options below
- double-click (ie. run) `qtlinguist-installers\windows\build-windows.ps1`
- that's it...

Your problem is maybe due to a configuration issue on your side. A Qt issue probably.

<img width="698" alt="qtinstall" src="https://user-images.githubusercontent.com/5641922/38457889-a412e148-3a96-11e8-9dea-7155014c5f0e.png">

**Comment by bovirus** [comment]
Thanks for the report.

Probably could be my QT configuration issue.

Is tehere a awy to pass to the .ps1 script the folder where the script find the files to build QTLinguist installer (ex. if you have both MinGW32 and MSVC2015 32bit compilers)?

Is there a way to run QT Linguist via command line forcing the loading a specific language?

Thanks.

**Comment by bovirus** [comment]
@lelegard 

Thanks. You can close this issue.
