### ISSUE TITLE
Separation between source and installer (Windows/Mac/Portable)

### ISSUE THREAD

**Issue by bovirus** [lelegard/qtlinguist-installers#6]
@lelegard 

Hi.

I believe that could be a good idea to seperate in the list of

https://github.com/lelegard/qtlinguist-installers/releases

the installer (Windows/Mac/Windows portable) from script source code.

This because QTLinguist installer has a version (5.9.0/59.1) but the source code is not related to QT SDK version.

In this way is not necessary to revise the script when it's available a new QT SDK version because the script should be independent by QT SDK version.

You can catalogue source code by release date as YYYY.MM.DD.

Thanks.

**Comment by lelegard** [comment]
Hi,

I understand your request. That would be relevant if I had written a large project with thousands of gorgeous code. But this is just a poor pair of small scripts, mostly copied/pasted from other projects I worked on. Nothing big, it does not deserve its own versioning.

Moreover, users do not care about the version of the scripts. They care about the Qt Linguist version (which is the same as the Qt version). This is why I prefer to keep the alignment with Qt versions so that users can immediately spot the right version of Qt Linguist.
